Teams Page
djunicode/Project-Finder pull request #13
Opened 2019-01-09 08:56 UTC by paceite

2019-01-12 14:30 UTC, shahp98 requested changes

2019-01-12 14:37 UTC, Kushald2805 commented on Ayush Shah/src/src/components/HackathonForm.js
> +import '../css/buddy.css';
Buddy doesn't have CDN

2019-01-12 15:10 UTC, shahp98 commented on Ayush Shah/src/src/components/HackathonForm.js
> +import '../css/buddy.css';
https://twitter.com/BuddyCSS/status/1029349288655110144

2019-01-12 15:11 UTC, shahp98 commented on Ayush Shah/src/src/components/HackathonForm.js
> +import '../css/buddy.css';
Apparently it does. In the latest version, they've added CDN Links.

2019-01-12 15:12 UTC, shahp98 commented on Ayush Shah/src/src/components/HackathonForm.js
> +import '../css/buddy.css';
`<link rel="stylesheet" type="text/css" href="https://buddycss-cc55.kxcdn.com/downloads/1.0.7/css/buddy.plugins.min.css">
<link rel="stylesheet" type="text/css" href="https://buddycss-cc55.kxcdn.com/downloads/1.0.7/css/buddy.min.css">
<script type="text/javascript" src="https://buddycss-cc55.kxcdn.com/downloads/1.0.7/js/buddy.min.js">`

2019-01-12 15:12 UTC, shahp98 commented on Ayush Shah/src/src/components/HackathonForm.js
> +import '../css/buddy.css';
`<link rel="stylesheet" type="text/css" href="https://buddycss-cc55.kxcdn.com/downloads/1.0.7/css/buddy.plugins.min.css">
<link rel="stylesheet" type="text/css" href="https://buddycss-cc55.kxcdn.com/downloads/1.0.7/css/buddy.min.css">
<script type="text/javascript" src="https://buddycss-cc55.kxcdn.com/downloads/1.0.7/js/buddy.min.js">`

2019-01-13 03:12 UTC, paceite commented on Ayush Shah/src/src/components/HackathonForm.js
> +import '../css/buddy.css';
The problem is we have to make a few changes in the buddy files itself...that won't be possible using cdn

2019-01-31 13:47 UTC, Kushald2805 commented
Push the latest code please

2019-01-31 14:52 UTC, paceite commented
Yes sure.

2019-02-08 13:12 UTC, Kushald2805 commented
You have missed out Accept and Decline options on the card of Teams Page. Rest everything is perfect.

2019-02-08 13:25 UTC, paceite commented
> You have missed out Accept and Decline options on the card of Teams Page.
> Search bar is missing too.

> You have missed out Accept and Decline options on the card of Teams Page.
> Search bar is missing too.

Oh shit yes...Accept and Decline part I saw that now...
Search bar I tried the design but it wasn't coming properly so I had left that out..will try it now

2019-02-22 18:07 UTC, Kushald2805 commented
Count on the top right corner is missing

2019-02-22 18:09 UTC, paceite commented
I'll check that and rectify it tomorrow

2019-02-23 06:24 UTC, paceite commented
I have added the count part....will resume figuring out multiple select form

2019-03-19 17:58 UTC, closed without merging